# Generated by Django 5.2.1 on 2025-05-09 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gruppi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commento',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gruppo',
            name='creatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gruppo',
            name='membri',
            field=models.ManyToManyField(related_name='gruppi_iscritti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='gruppo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruppi.gruppo'),
        ),
        migrations.AddField(
            model_name='post',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commento',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruppi.post'),
        ),
    ]
